// Generated by gencpp from file ur_planning/grasp_pose.msg
// DO NOT EDIT!


#ifndef UR_PLANNING_MESSAGE_GRASP_POSE_H
#define UR_PLANNING_MESSAGE_GRASP_POSE_H

#include <ros/service_traits.h>


#include <ur_planning/grasp_poseRequest.h>
#include <ur_planning/grasp_poseResponse.h>


namespace ur_planning
{

struct grasp_pose
{

typedef grasp_poseRequest Request;
typedef grasp_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct grasp_pose
} // namespace ur_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_planning::grasp_pose > {
  static const char* value()
  {
    return "8a5978aa25b0b059ee08ab4584d6c721";
  }

  static const char* value(const ::ur_planning::grasp_pose&) { return value(); }
};

template<>
struct DataType< ::ur_planning::grasp_pose > {
  static const char* value()
  {
    return "ur_planning/grasp_pose";
  }

  static const char* value(const ::ur_planning::grasp_pose&) { return value(); }
};


// service_traits::MD5Sum< ::ur_planning::grasp_poseRequest> should match
// service_traits::MD5Sum< ::ur_planning::grasp_pose >
template<>
struct MD5Sum< ::ur_planning::grasp_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_planning::grasp_pose >::value();
  }
  static const char* value(const ::ur_planning::grasp_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_planning::grasp_poseRequest> should match
// service_traits::DataType< ::ur_planning::grasp_pose >
template<>
struct DataType< ::ur_planning::grasp_poseRequest>
{
  static const char* value()
  {
    return DataType< ::ur_planning::grasp_pose >::value();
  }
  static const char* value(const ::ur_planning::grasp_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_planning::grasp_poseResponse> should match
// service_traits::MD5Sum< ::ur_planning::grasp_pose >
template<>
struct MD5Sum< ::ur_planning::grasp_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_planning::grasp_pose >::value();
  }
  static const char* value(const ::ur_planning::grasp_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_planning::grasp_poseResponse> should match
// service_traits::DataType< ::ur_planning::grasp_pose >
template<>
struct DataType< ::ur_planning::grasp_poseResponse>
{
  static const char* value()
  {
    return DataType< ::ur_planning::grasp_pose >::value();
  }
  static const char* value(const ::ur_planning::grasp_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_PLANNING_MESSAGE_GRASP_POSE_H
