; Auto-generated. Do not edit!


(cl:in-package jaka_moveit_action-msg)


;//! \htmlinclude jakacontrollerResult.msg.html

(cl:defclass <jakacontrollerResult> (roslisp-msg-protocol:ros-message)
  ((robot_pose
    :reader robot_pose
    :initarg :robot_pose
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass jakacontrollerResult (<jakacontrollerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <jakacontrollerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'jakacontrollerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jaka_moveit_action-msg:<jakacontrollerResult> is deprecated: use jaka_moveit_action-msg:jakacontrollerResult instead.")))

(cl:ensure-generic-function 'robot_pose-val :lambda-list '(m))
(cl:defmethod robot_pose-val ((m <jakacontrollerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jaka_moveit_action-msg:robot_pose-val is deprecated.  Use jaka_moveit_action-msg:robot_pose instead.")
  (robot_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <jakacontrollerResult>) ostream)
  "Serializes a message object of type '<jakacontrollerResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'robot_pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <jakacontrollerResult>) istream)
  "Deserializes a message object of type '<jakacontrollerResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<jakacontrollerResult>)))
  "Returns string type for a message object of type '<jakacontrollerResult>"
  "jaka_moveit_action/jakacontrollerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'jakacontrollerResult)))
  "Returns string type for a message object of type 'jakacontrollerResult"
  "jaka_moveit_action/jakacontrollerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<jakacontrollerResult>)))
  "Returns md5sum for a message object of type '<jakacontrollerResult>"
  "3b48096e908b69eba74b15382d074a06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'jakacontrollerResult)))
  "Returns md5sum for a message object of type 'jakacontrollerResult"
  "3b48096e908b69eba74b15382d074a06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<jakacontrollerResult>)))
  "Returns full string definition for message of type '<jakacontrollerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32[] robot_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'jakacontrollerResult)))
  "Returns full string definition for message of type 'jakacontrollerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32[] robot_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <jakacontrollerResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <jakacontrollerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'jakacontrollerResult
    (cl:cons ':robot_pose (robot_pose msg))
))
