// Auto-generated. Do not edit!

// (in-package jaka_moveit_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class jakacontrollerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.point_count = null;
      this.robot_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('point_count')) {
        this.point_count = initObj.point_count
      }
      else {
        this.point_count = 0;
      }
      if (initObj.hasOwnProperty('robot_goal')) {
        this.robot_goal = initObj.robot_goal
      }
      else {
        this.robot_goal = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type jakacontrollerGoal
    // Serialize message field [point_count]
    bufferOffset = _serializer.int16(obj.point_count, buffer, bufferOffset);
    // Serialize message field [robot_goal]
    bufferOffset = _arraySerializer.float32(obj.robot_goal, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type jakacontrollerGoal
    let len;
    let data = new jakacontrollerGoal(null);
    // Deserialize message field [point_count]
    data.point_count = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [robot_goal]
    data.robot_goal = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.robot_goal.length;
    return length + 6;
  }

  static datatype() {
    // Returns string type for a message object
    return 'jaka_moveit_action/jakacontrollerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1267157bce955f9c70f78d5247a3d8c7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    int16 point_count
    float32[] robot_goal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new jakacontrollerGoal(null);
    if (msg.point_count !== undefined) {
      resolved.point_count = msg.point_count;
    }
    else {
      resolved.point_count = 0
    }

    if (msg.robot_goal !== undefined) {
      resolved.robot_goal = msg.robot_goal;
    }
    else {
      resolved.robot_goal = []
    }

    return resolved;
    }
};

module.exports = jakacontrollerGoal;
