// Auto-generated. Do not edit!

// (in-package jaka_moveit_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class jakacontrollerResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.robot_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('robot_pose')) {
        this.robot_pose = initObj.robot_pose
      }
      else {
        this.robot_pose = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type jakacontrollerResult
    // Serialize message field [robot_pose]
    bufferOffset = _arraySerializer.float32(obj.robot_pose, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type jakacontrollerResult
    let len;
    let data = new jakacontrollerResult(null);
    // Deserialize message field [robot_pose]
    data.robot_pose = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.robot_pose.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'jaka_moveit_action/jakacontrollerResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3b48096e908b69eba74b15382d074a06';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    float32[] robot_pose
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new jakacontrollerResult(null);
    if (msg.robot_pose !== undefined) {
      resolved.robot_pose = msg.robot_pose;
    }
    else {
      resolved.robot_pose = []
    }

    return resolved;
    }
};

module.exports = jakacontrollerResult;
