jakaUr:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

JAKA_Robot/gazebo_ros_control/pid_gains:
      joint_1:   {p: 100, i: 0.01, d: 10.0}
      joint_2:   {p: 100, i: 0.01, d: 10.0}
      joint_3:   {p: 100, i: 0.01, d: 10.0}
      joint_4:   {p: 100, i: 0.01, d: 10.0}
      joint_5:   {p: 100, i: 0.01, d: 10.0}
      joint_6:   {p: 100, i: 0.01, d: 10.0}
