// Generated by gencpp from file jaka_moveit_action/jakacontrollerResult.msg
// DO NOT EDIT!


#ifndef JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERRESULT_H
#define JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaka_moveit_action
{
template <class ContainerAllocator>
struct jakacontrollerResult_
{
  typedef jakacontrollerResult_<ContainerAllocator> Type;

  jakacontrollerResult_()
    : robot_pose()  {
    }
  jakacontrollerResult_(const ContainerAllocator& _alloc)
    : robot_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _robot_pose_type;
  _robot_pose_type robot_pose;





  typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> const> ConstPtr;

}; // struct jakacontrollerResult_

typedef ::jaka_moveit_action::jakacontrollerResult_<std::allocator<void> > jakacontrollerResult;

typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerResult > jakacontrollerResultPtr;
typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerResult const> jakacontrollerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator1> & lhs, const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator2> & rhs)
{
  return lhs.robot_pose == rhs.robot_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator1> & lhs, const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaka_moveit_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b48096e908b69eba74b15382d074a06";
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b48096e908b69ebULL;
  static const uint64_t static_value2 = 0xa74b15382d074a06ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaka_moveit_action/jakacontrollerResult";
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"float32[] robot_pose\n"
;
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jakacontrollerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaka_moveit_action::jakacontrollerResult_<ContainerAllocator>& v)
  {
    s << indent << "robot_pose[]" << std::endl;
    for (size_t i = 0; i < v.robot_pose.size(); ++i)
    {
      s << indent << "  robot_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.robot_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERRESULT_H
