// Generated by gencpp from file jaka_moveit_action/jakacontrollerAction.msg
// DO NOT EDIT!


#ifndef JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERACTION_H
#define JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jaka_moveit_action/jakacontrollerActionGoal.h>
#include <jaka_moveit_action/jakacontrollerActionResult.h>
#include <jaka_moveit_action/jakacontrollerActionFeedback.h>

namespace jaka_moveit_action
{
template <class ContainerAllocator>
struct jakacontrollerAction_
{
  typedef jakacontrollerAction_<ContainerAllocator> Type;

  jakacontrollerAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  jakacontrollerAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::jaka_moveit_action::jakacontrollerActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::jaka_moveit_action::jakacontrollerActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::jaka_moveit_action::jakacontrollerActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> const> ConstPtr;

}; // struct jakacontrollerAction_

typedef ::jaka_moveit_action::jakacontrollerAction_<std::allocator<void> > jakacontrollerAction;

typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerAction > jakacontrollerActionPtr;
typedef boost::shared_ptr< ::jaka_moveit_action::jakacontrollerAction const> jakacontrollerActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator1> & lhs, const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator1> & lhs, const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaka_moveit_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d96b335a5bba30675f635b25b0f73f5";
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d96b335a5bba306ULL;
  static const uint64_t static_value2 = 0x75f635b25b0f73f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaka_moveit_action/jakacontrollerAction";
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"jakacontrollerActionGoal action_goal\n"
"jakacontrollerActionResult action_result\n"
"jakacontrollerActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"jakacontrollerGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"int16 point_count\n"
"float32[] robot_goal\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"jakacontrollerResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"float32[] robot_pose\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"jakacontrollerFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: jaka_moveit_action/jakacontrollerFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"int16 point_num\n"
"float32[] robot_now\n"
"\n"
;
  }

  static const char* value(const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jakacontrollerAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaka_moveit_action::jakacontrollerAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::jaka_moveit_action::jakacontrollerActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::jaka_moveit_action::jakacontrollerActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::jaka_moveit_action::jakacontrollerActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JAKA_MOVEIT_ACTION_MESSAGE_JAKACONTROLLERACTION_H
